# -*- coding: utf-8 -*-
"""SalaryPredictor-LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FU6QTLiBz36-_9B03UbFJ1ZwfUQ-hHYP
"""

import pandas as pd

df = pd.read_csv("Salary_Data.csv")

df.shape

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt

# %matplotlib inline
plt.xlabel('No of Years')
plt.ylabel("Salary")
plt.scatter(df.YearsExperience, df.Salary, color='red', marker='+')

from sklearn import linear_model

model = linear_model.LinearRegression()

model.fit(df[['YearsExperience']], df.Salary)

model.predict([[4.5]])



model.coef_

model.intercept_

9449.96232146 * 4.5 + 25792.200198668696

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt

# %matplotlib inline
plt.xlabel('No of Years')
plt.ylabel("Salary")
plt.scatter(df.YearsExperience, df.Salary, color='red', marker='+')
plt.plot(df.YearsExperience, model.predict(df[['YearsExperience']]))

dd = pd.read_csv("predict_salary.csv")

dd

prediction =  model.predict(dd[['Years']])

prediction

dd['Salary'] = prediction

dd

dd.to_csv('prediction.csv', index=False)