# -*- coding: utf-8 -*-
"""StartupProfitPredictor-LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SiyLDdYGr3yi916ubIR8RABa68qkb6z5
"""

import pandas as pd

df = pd.read_csv('50_Startups.csv')


df.head(3)

#write algo to convert state into index
allStates = []

for state in df['State']:
  if state not in allStates:
    allStates.append(state)

allStates

newStates = []

for state in df['State']:
  newStates.append(allStates.index(state))

len(newStates)

df['State'] = newStates

df.head(5)



from sklearn import linear_model

model = linear_model.LinearRegression()

model.fit(df[['R&D Spend', 'Administration', 'Marketing Spend', 'State']], df.Profit)

model.predict([[153441.51, 101145.55, 443898.53, 0]])

model.coef_

model.intercept_